/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroB2bRouteImport } from './routes/cadastro-b2b'
import { Route as CadastroAssinaturaRouteImport } from './routes/cadastro-assinatura'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as KitSlugRouteImport } from './routes/kit.$slug'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminKitsRouteImport } from './routes/admin.kits'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminPedidosNovoRouteImport } from './routes/admin.pedidos.novo'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroB2bRoute = CadastroB2bRouteImport.update({
  id: '/cadastro-b2b',
  path: '/cadastro-b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAssinaturaRoute = CadastroAssinaturaRouteImport.update({
  id: '/cadastro-assinatura',
  path: '/cadastro-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const KitSlugRoute = KitSlugRouteImport.update({
  id: '/kit/$slug',
  path: '/kit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitsRoute = AdminKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosNovoRoute = AdminPedidosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro-assinatura': typeof CadastroAssinaturaRoute
  '/cadastro-b2b': typeof CadastroB2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-assinatura': typeof CadastroAssinaturaRoute
  '/cadastro-b2b': typeof CadastroB2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro-assinatura': typeof CadastroAssinaturaRoute
  '/cadastro-b2b': typeof CadastroB2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/kits': typeof AdminKitsRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/produtos': typeof AdminProdutosRoute
  '/kit/$slug': typeof KitSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro-assinatura'
    | '/cadastro-b2b'
    | '/carrinho'
    | '/categorias'
    | '/kits'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/kits'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/kit/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro-assinatura'
    | '/cadastro-b2b'
    | '/carrinho'
    | '/categorias'
    | '/kits'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/kits'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/kit/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro-assinatura'
    | '/cadastro-b2b'
    | '/carrinho'
    | '/categorias'
    | '/kits'
    | '/login'
    | '/minha-conta'
    | '/produtos'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/kits'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/kit/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/pedidos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroAssinaturaRoute: typeof CadastroAssinaturaRoute
  CadastroB2bRoute: typeof CadastroB2bRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CategoriasRoute: typeof CategoriasRoute
  KitsRoute: typeof KitsRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ProdutosRoute: typeof ProdutosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KitSlugRoute: typeof KitSlugRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-b2b': {
      id: '/cadastro-b2b'
      path: '/cadastro-b2b'
      fullPath: '/cadastro-b2b'
      preLoaderRoute: typeof CadastroB2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-assinatura': {
      id: '/cadastro-assinatura'
      path: '/cadastro-assinatura'
      fullPath: '/cadastro-assinatura'
      preLoaderRoute: typeof CadastroAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/$slug': {
      id: '/kit/$slug'
      path: '/kit/$slug'
      fullPath: '/kit/$slug'
      preLoaderRoute: typeof KitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kits': {
      id: '/admin/kits'
      path: '/kits'
      fullPath: '/admin/kits'
      preLoaderRoute: typeof AdminKitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/novo': {
      id: '/admin/pedidos/novo'
      path: '/novo'
      fullPath: '/admin/pedidos/novo'
      preLoaderRoute: typeof AdminPedidosNovoRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
  }
}

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosNovoRoute: typeof AdminPedidosNovoRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosNovoRoute: AdminPedidosNovoRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminKitsRoute: typeof AdminKitsRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminKitsRoute: AdminKitsRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroAssinaturaRoute: CadastroAssinaturaRoute,
  CadastroB2bRoute: CadastroB2bRoute,
  CarrinhoRoute: CarrinhoRoute,
  CategoriasRoute: CategoriasRoute,
  KitsRoute: KitsRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  ProdutosRoute: ProdutosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KitSlugRoute: KitSlugRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
